### ISSUE TITLE
Points not showing

### ISSUE THREAD

**Issue by Orrelous** [DatBear/Guardians-of-the-Rift-Helper#14]
I started these games with a fresh slate of 0/0 points, and no matter how many games i have done since yesterday my points have been stuck at 0/0, even now when they should show 1/17
![2022-04-13_20-27-54](https://user-images.githubusercontent.com/103620223/163308832-5ca67cf4-a88a-497b-98fe-61aa1aaa8902.png)
6

**Comment by ulises-c** [comment]
Points go negative aftersearching guardian

![2022-04-14_18-48-39](https://user-images.githubusercontent.com/13595269/163505032-8249aa13-01cc-444d-a26b-1af799cc3237.png)

**Comment by beau-witter** [comment]
Looks like it is specifically this regex:
`private static final String REWARD_POINT_REGEX = "Elemental attunement level:[^>]+>(\\d+).*Catalytic attunement level:[^>]+>(\\d+)";`
which is line 81 in `GuardiansOfTheRiftHelperPlugin.java`
Should probably be:
`private static final String REWARD_POINT_REGEX = "Total elemental energy:[^>]+>(\\d+).*Total catalytic energy:[^>]+>(\\d+).";`
