### ISSUE TITLE
Reward point counter does not increase

### ISSUE THREAD

**Issue by The-da-vinci** [DatBear/Guardians-of-the-Rift-Helper#17]
![Picture of Reward point counter](https://i.imgur.com/p36efBW.png)

Like we can see in the picture, the reward point counter does not increase, only decreases.

**Comment by Tizby101** [comment]
It looks like it doesn't keep track of the currently reward points, but it keeps track of when rewards are spent.

**Comment by skow1379** [comment]
Also having this problem. Tried uninstalling reinstalling multiple times with opening and closing runelite. It's driving me nuts

**Comment by erisve1337** [comment]
Same here, still an issue

**Comment by Orrelous** [comment]
I am also still having this issue

**Comment by Jagerblue** [comment]
@DatBear you will need to update the manifest to reflect the newest commit, the PR's you've accepted fixing these issues have not been applied to the live plugin-hub

**Comment by DatBear** [comment]
Updated!
