### ISSUE TITLE
Portal location is missing from notification text

### ISSUE THREAD

**Issue by nmehta94** [DatBear/Guardians-of-the-Rift-Helper#19]
![image](https://user-images.githubusercontent.com/8924734/167473739-c80e84a0-535a-4a53-8675-30980d87471a.png)

**Comment by Irets** [comment]
This issue is also present in desktop notifications.
![maim_1652570778](https://user-images.githubusercontent.com/50279814/168451267-ee074f35-6ef8-4de7-899c-adcb111e30a3.png)

**Comment by awoo93** [comment]
Also have this issue.
![image](https://user-images.githubusercontent.com/108483563/176733383-0a1c5b31-9f23-4e95-b816-50217d49967e.png)

**Comment by akeith997** [comment]
Having this issue as well. 
https://i.imgur.com/vhdtpn7.png
