### ISSUE TITLE
Overlay doesn't disappear

### ISSUE THREAD

**Issue by ulises-c** [DatBear/Guardians-of-the-Rift-Helper#2]
There should be some sort of inactivity timer or area detection that disables the plugin or at least removes the overlay

**Comment by DatBear** [comment]
This should happen if you leave the area. Is it not going away for you when you leave the minigame area?

**Comment by ulises-c** [comment]
It is not disappearing. Here I've left the area and the overlay is still there 
![image](https://user-images.githubusercontent.com/13595269/161009180-ed9b6246-97c7-4be6-ba0a-fee17a322418.png)

**Comment by PiraatSchaap** [comment]
Happening to me too, left normally through the exit portal
![image](https://i.imgur.com/Axs4lMj.jpeg)

**Comment by LucasChilders** [comment]
Attempted fix here: https://github.com/DatBear/Guardians-of-the-Rift-Helper/pull/18

**Comment by nmehta94** [comment]
+1 still happens to me

**Comment by WhiteCat22** [comment]
I'd like to see the overlay at least hidden when the bank is open or behind the bank window

**Comment by JonathanOuwens** [comment]
Still not fixed :(

**Comment by AlexFromIT** [comment]
I'm still having this issue. Was doing gotr, teleported away, and the overlay was still there. Tried logging out for a bit just to come back and see that the overlay was still there.

![Image](https://github.com/user-attachments/assets/f6257d5b-2810-4b73-b4bc-f420b37d2ae8)
