### ISSUE TITLE
Remove the overlay after leaving the minigame area

### ISSUE THREAD

**Issue by Fjara-h** [DatBear/Guardians-of-the-Rift-Helper#32]
Currently the overlay only activates when you enter the rift dimension area, but it should also hide upon leaving or check every so often after time to see if you are in the area still otherwise the overall persists until reloading RL.

**Comment by DatBear** [comment]
I think this has been fixed?

**Comment by DatBear** [comment]
![image](https://github.com/user-attachments/assets/c4b9b842-8108-46d0-aa4b-2ae66b130c66)
