### ISSUE TITLE
[Suggestion] Game about to start notification

### ISSUE THREAD

**Issue by jacobholden** [DatBear/Guardians-of-the-Rift-Helper#34]
Make a notification for when a game's about to start :)

**Comment by olliekabi** [comment]
I've made a branch with this feature and a config toggle for it. If the maintainer gives me push access I'll push the branch up and open a pull request.

**Comment by CypherD** [comment]
I'd love to see this get added. It'd be super useful since most people tend to afk between rounds

**Comment by caleyz** [comment]
I know this is an old thread but for anyone that stumbles upon this - you can set a notification to go off with the Chat Notifications plugin and put in the message  The rift will become active in 5 seconds.   and you'll get your notification.
