### ISSUE TITLE
"Show Start Timer Overlay" no longer appearing

### ISSUE THREAD

**Issue by kylev12341234** [DatBear/Guardians-of-the-Rift-Helper#44]
At some point it just stopped appearing. tried reinstalling and resetting, did not work.

![image](https://user-images.githubusercontent.com/126594005/221902166-b4406877-8cb5-4dc3-9d8a-f099ca78d935.png)

**Comment by kylev12341234** [comment]
asked around in game and someone else also lately starting having this issue

**Comment by netstormuk** [comment]
https://github.com/DatBear/Guardians-of-the-Rift-Helper/issues/43#issuecomment-1447610155
