### ISSUE TITLE
[Bug] Outline Great Guardian doesn't work until an item is added/removed

### ISSUE THREAD

**Issue by CreativeTechGuy** [DatBear/Guardians-of-the-Rift-Helper#45]
Since a recent update (unclear if this was a Runelite change or a plugin change), the outline of the Great Guardian is broken. The Great Guardian isn't outlined immediately upon returning from an altar. Instead they are only outlined once an item has been first added/removed from the inventory

I believe I've traced it to the exact lines of code involved if that'll help.

* For the guardian to render, [this must be true](https://github.com/DatBear/Guardians-of-the-Rift-Helper/blob/29b4d0ba4c025d60846e51fc1726f03fde245fc3/src/main/java/com/datbear/GuardiansOfTheRiftHelperPlugin.java#L210). This line is fine, but will only execute `onItemContainerChanged` but only when `isInMainRegion`.
* `isInMainRegion` [is only set `onGameTick`](https://github.com/DatBear/Guardians-of-the-Rift-Helper/blob/29b4d0ba4c025d60846e51fc1726f03fde245fc3/src/main/java/com/datbear/GuardiansOfTheRiftHelperPlugin.java#L224) and regardless of it's value changing, the previous conditions are never re-checked.

When you craft runes, you aren't in the main region so that check is false. But when you arrive back in the main region, the code isn't reevaluated when you change regions and therefore only updates when you have an inventory event.

I'm not sure the solution without testing it, but it seems like if the `isInMainRegion` check was changed to `checkInMinigame()` (assuming that function isn't too expensive), that could work. Or there might be another hook which should be used instead for when the region changes.

**Comment by CreativeTechGuy** [comment]
This same issue also affects inventory talisman highlighting due to the same reason.

**Comment by otygah** [comment]
I'm still getting this issue :/
