### ISSUE TITLE
Portal talisman icon displays incorrectly when multiple different types acquired

### ISSUE THREAD

**Issue by taydell** [DatBear/Guardians-of-the-Rift-Helper#58]
recreation steps
1. get portal talisman 1(this example is earth)
2. get portal talisman 2(this example is fire)
3. drop portal talisman 1
4. display shows talisman icon 1 over portal not talisman icon 2

![gotr error](https://github.com/DatBear/Guardians-of-the-Rift-Helper/assets/11182517/0757851b-70f0-4d38-b369-887932ecd873)

**Comment by taydell** [comment]
After further attempts at recreating it i only managed to do it 1 other time. so idk how i did it

**Comment by gtjamesa** [comment]
This has happened to me a few times and I would say the reproduction instructions sound correct from memory
